// Copyright 2022 Linka Cloud  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"fmt"
	"strings"
	"text/template"

	pgs "github.com/lyft/protoc-gen-star"
	pgsgo "github.com/lyft/protoc-gen-star/lang/go"
	"github.com/sirupsen/logrus"

	"go.linka.cloud/grpc-rbac/rbac"
)

func Module() *module {
	return &module{
		ModuleBase: &pgs.ModuleBase{},
	}
}

type module struct {
	*pgs.ModuleBase
	ctx pgsgo.Context
	tpl *template.Template
}

func (p *module) Name() string {
	return "rbac"
}

func (p *module) InitContext(c pgs.BuildContext) {
	p.ModuleBase.InitContext(c)
	p.ctx = pgsgo.InitContext(c.Parameters())

	type role struct {
		Name  string
		Value string
		Perms []string
	}

	tpl := template.New("fields").Funcs(map[string]interface{}{
		"package": p.ctx.PackageName,
		"name":    p.ctx.Name,
		"comment": func(s string) string {
			var out string
			parts := strings.Split(s, "\n")
			for i, v := range parts {
				if i == len(parts)-1 && v == "" {
					return out
				}
				out += "//" + v + "\n"
			}
			return out
		},
		"roles": func(s pgs.Service) []*role {
			roles := make(map[string]*role)
			for _, m := range s.Methods() {
				o := &rbac.RBAC{}
				ok, err := m.Extension(rbac.E_Rbac, o)
				if err != nil {
					p.Fail(err)
				}
				if !ok {
					continue
				}
				for _, v := range o.Roles {
					val := fmt.Sprintf("%s.%s", s.Name(), strings.Title(v))
					if _, ok := roles[val]; !ok {
						logrus.Infof("adding role %s", val)
						roles[val] = &role{
							Name:  strings.Replace(strings.Title(strings.NewReplacer(".", " ", "-", " ", ":", " ", "_", " ").Replace(v)), " ", "", -1),
							Value: val,
						}
					}
					logrus.Infof("%s: permitting %s", val, m.Name())
					roles[val].Perms = append(roles[val].Perms, m.Name().String())
				}
			}
			var out []*role
			for _, v := range roles {
				out = append(out, v)
			}
			return out
		},
	})
	p.tpl = template.Must(tpl.Parse(fieldsTpl))
}

func (p *module) Execute(targets map[string]pgs.File, _ map[string]pgs.Package) []pgs.Artifact {
	for _, f := range targets {
		p.generate(f)
	}
	return p.Artifacts()
}

func (p *module) generate(f pgs.File) {
	if len(f.Services()) == 0 {
		return
	}
	name := p.ctx.OutputPath(f).SetExt(".rbac.go")
	p.AddGeneratorTemplateFile(name.String(), p.tpl, f)
}

const fieldsTpl = `{{ comment .SyntaxSourceCodeInfo.LeadingComments }}
{{ range .SyntaxSourceCodeInfo.LeadingDetachedComments }}
{{ comment . }}
{{ end }}
// Code generated by protoc-gen-go-rbac. DO NOT EDIT.
package {{ package . }}
{{ $file := . }}
import (
	grpc_rbac "go.linka.cloud/grpc-rbac"
)

{{ range .Services }}
{{- $svc := . }} 
var {{ .Name }}Permissions = struct {
	{{- range .Methods }}
	{{ name . }} grpc_rbac.Permission
	{{- end }}
}{
	{{- range .Methods }}
	{{ name . }}: grpc_rbac.NewGRPCPermission("{{ $file.Package.ProtoName }}.{{ $svc.Name }}", "{{ .Name }}"),
	{{- end }}
}

var {{ .Name }}Roles = struct {
	{{- range roles . }}
	{{ .Name }} *grpc_rbac.StdRole
	{{- end }}
}{
	{{- range roles . }}
	{{ .Name }}: grpc_rbac.NewStdRole("{{ .Value }}"),
	{{- end }}
}

func Register{{ .Name }}Permissions(rbac grpc_rbac.RBAC) {
	{{- range roles . }}
	{{- $role := . }}
	{{- range .Perms }}
	{{ $svc.Name }}Roles.{{ $role.Name }}.Assign({{ $svc.Name }}Permissions.{{ . }})
	{{- end }}
	rbac.Add({{ $svc.Name }}Roles.{{ .Name }})
	
	{{end }}
	rbac.Register(&{{ .Name }}_ServiceDesc)
}

{{ end }}
`
