// Copyright 2022 Linka Cloud  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-rbac. DO NOT EDIT.
package example

import (
	grpc_rbac "go.linka.cloud/grpc-rbac"
)

var ResourceServicePermissions = struct {
	Create grpc_rbac.Permission
	Read   grpc_rbac.Permission
	Update grpc_rbac.Permission
	Delete grpc_rbac.Permission
	List   grpc_rbac.Permission
	Watch  grpc_rbac.Permission
}{
	Create: grpc_rbac.NewGRPCPermission("example.ResourceService", "Create"),
	Read:   grpc_rbac.NewGRPCPermission("example.ResourceService", "Read"),
	Update: grpc_rbac.NewGRPCPermission("example.ResourceService", "Update"),
	Delete: grpc_rbac.NewGRPCPermission("example.ResourceService", "Delete"),
	List:   grpc_rbac.NewGRPCPermission("example.ResourceService", "List"),
	Watch:  grpc_rbac.NewGRPCPermission("example.ResourceService", "Watch"),
}

var ResourceServiceRoles = struct {
	Admin   *grpc_rbac.StdRole
	Reader  *grpc_rbac.StdRole
	Watcher *grpc_rbac.StdRole
	Writer  *grpc_rbac.StdRole
}{
	Admin:   grpc_rbac.NewStdRole("ResourceService.Admin"),
	Reader:  grpc_rbac.NewStdRole("ResourceService.Reader"),
	Watcher: grpc_rbac.NewStdRole("ResourceService.Watcher"),
	Writer:  grpc_rbac.NewStdRole("ResourceService.Writer"),
}

func RegisterResourceServicePermissions(rbac grpc_rbac.RBAC) {
	// Register Admin role
	if err := rbac.Add(ResourceServiceRoles.Admin); err != nil {
		panic(err)
	}

	// Assign Reader permissions
	if err := ResourceServiceRoles.Reader.Assign(ResourceServicePermissions.Read); err != nil {
		panic(err)
	}
	if err := ResourceServiceRoles.Reader.Assign(ResourceServicePermissions.List); err != nil {
		panic(err)
	}
	// Register Reader role
	if err := rbac.Add(ResourceServiceRoles.Reader); err != nil {
		panic(err)
	}

	// Assign Watcher permissions
	if err := ResourceServiceRoles.Watcher.Assign(ResourceServicePermissions.Watch); err != nil {
		panic(err)
	}
	// Register Watcher role
	if err := rbac.Add(ResourceServiceRoles.Watcher); err != nil {
		panic(err)
	}

	// Assign Writer permissions
	if err := ResourceServiceRoles.Writer.Assign(ResourceServicePermissions.Create); err != nil {
		panic(err)
	}
	if err := ResourceServiceRoles.Writer.Assign(ResourceServicePermissions.Update); err != nil {
		panic(err)
	}
	if err := ResourceServiceRoles.Writer.Assign(ResourceServicePermissions.Delete); err != nil {
		panic(err)
	}
	// Register Writer role
	if err := rbac.Add(ResourceServiceRoles.Writer); err != nil {
		panic(err)
	}

	// Assign Admin parents
	if err := rbac.SetParent(ResourceServiceRoles.Admin.ID(), ResourceServiceRoles.Writer.ID()); err != nil {
		panic(err)
	}
	if err := rbac.SetParent(ResourceServiceRoles.Admin.ID(), ResourceServiceRoles.Reader.ID()); err != nil {
		panic(err)
	}
	if err := rbac.SetParent(ResourceServiceRoles.Admin.ID(), ResourceServiceRoles.Watcher.ID()); err != nil {
		panic(err)
	}

	// Register ResourceService Service rules
	rbac.Register(&ResourceService_ServiceDesc)
}
