// Copyright 2022 Linka Cloud  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-rbac. DO NOT EDIT.
package example

import (
	grpc_rbac "go.linka.cloud/grpc-rbac"
)

var ResourceServicePermissions = struct {
	Create grpc_rbac.Permission
	Read   grpc_rbac.Permission
	Update grpc_rbac.Permission
	Delete grpc_rbac.Permission
	List   grpc_rbac.Permission
	Watch  grpc_rbac.Permission
}{
	Create: grpc_rbac.NewGRPCPermission("example.ResourceService", "Create"),
	Read:   grpc_rbac.NewGRPCPermission("example.ResourceService", "Read"),
	Update: grpc_rbac.NewGRPCPermission("example.ResourceService", "Update"),
	Delete: grpc_rbac.NewGRPCPermission("example.ResourceService", "Delete"),
	List:   grpc_rbac.NewGRPCPermission("example.ResourceService", "List"),
	Watch:  grpc_rbac.NewGRPCPermission("example.ResourceService", "Watch"),
}

var ResourceServiceRoles = struct {
	Watcher *grpc_rbac.StdRole
	Admin   *grpc_rbac.StdRole
	Writer  *grpc_rbac.StdRole
	Reader  *grpc_rbac.StdRole
}{
	Admin:   grpc_rbac.NewStdRole("ResourceService.Admin"),
	Writer:  grpc_rbac.NewStdRole("ResourceService.Writer"),
	Reader:  grpc_rbac.NewStdRole("ResourceService.Reader"),
	Watcher: grpc_rbac.NewStdRole("ResourceService.Watcher"),
}

func RegisterResourceServicePermissions(rbac grpc_rbac.RBAC) {
	ResourceServiceRoles.Admin.Assign(ResourceServicePermissions.Create)
	ResourceServiceRoles.Admin.Assign(ResourceServicePermissions.Read)
	ResourceServiceRoles.Admin.Assign(ResourceServicePermissions.Update)
	ResourceServiceRoles.Admin.Assign(ResourceServicePermissions.Delete)
	ResourceServiceRoles.Admin.Assign(ResourceServicePermissions.List)
	ResourceServiceRoles.Admin.Assign(ResourceServicePermissions.Watch)
	rbac.Add(ResourceServiceRoles.Admin)

	ResourceServiceRoles.Writer.Assign(ResourceServicePermissions.Create)
	ResourceServiceRoles.Writer.Assign(ResourceServicePermissions.Update)
	ResourceServiceRoles.Writer.Assign(ResourceServicePermissions.Delete)
	rbac.Add(ResourceServiceRoles.Writer)

	ResourceServiceRoles.Reader.Assign(ResourceServicePermissions.Read)
	ResourceServiceRoles.Reader.Assign(ResourceServicePermissions.List)
	rbac.Add(ResourceServiceRoles.Reader)

	ResourceServiceRoles.Watcher.Assign(ResourceServicePermissions.Watch)
	rbac.Add(ResourceServiceRoles.Watcher)

	rbac.Register(&ResourceService_ServiceDesc)
}
