// Copyright 2022 Linka Cloud  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-rbac. DO NOT EDIT.
package example

import (
	grpc_rbac "go.linka.cloud/grpc-rbac"
)

var ResourceServicePermissions = struct {
	Create grpc_rbac.Permission
	Read   grpc_rbac.Permission
	Update grpc_rbac.Permission
	Delete grpc_rbac.Permission
	List   grpc_rbac.Permission
	Watch  grpc_rbac.Permission
}{
	Create: grpc_rbac.NewGRPCPermission("example.ResourceService", "Create"),
	Read:   grpc_rbac.NewGRPCPermission("example.ResourceService", "Read"),
	Update: grpc_rbac.NewGRPCPermission("example.ResourceService", "Update"),
	Delete: grpc_rbac.NewGRPCPermission("example.ResourceService", "Delete"),
	List:   grpc_rbac.NewGRPCPermission("example.ResourceService", "List"),
	Watch:  grpc_rbac.NewGRPCPermission("example.ResourceService", "Watch"),
}

func RegisterResourceServicePermissions(rbac grpc_rbac.RBAC) {
	rbac.Register(&ResourceService_ServiceDesc)
}
